/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleExperimentsIndexRouteImport } from './routes/$locale/experiments/index'
import { Route as LocaleWorkSlugRouteImport } from './routes/$locale/work/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/$locale/',
  path: '/$locale/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleExperimentsIndexRoute = LocaleExperimentsIndexRouteImport.update({
  id: '/$locale/experiments/',
  path: '/$locale/experiments/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleWorkSlugRoute = LocaleWorkSlugRouteImport.update({
  id: '/$locale/work/$slug',
  path: '/$locale/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/work/$slug': typeof LocaleWorkSlugRoute
  '/$locale/experiments/': typeof LocaleExperimentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/work/$slug': typeof LocaleWorkSlugRoute
  '/$locale/experiments': typeof LocaleExperimentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/work/$slug': typeof LocaleWorkSlugRoute
  '/$locale/experiments/': typeof LocaleExperimentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$locale/' | '/$locale/work/$slug' | '/$locale/experiments/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$locale' | '/$locale/work/$slug' | '/$locale/experiments'
  id:
    | '__root__'
    | '/'
    | '/$locale/'
    | '/$locale/work/$slug'
    | '/$locale/experiments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleWorkSlugRoute: typeof LocaleWorkSlugRoute
  LocaleExperimentsIndexRoute: typeof LocaleExperimentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/$locale'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/experiments/': {
      id: '/$locale/experiments/'
      path: '/$locale/experiments'
      fullPath: '/$locale/experiments/'
      preLoaderRoute: typeof LocaleExperimentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/work/$slug': {
      id: '/$locale/work/$slug'
      path: '/$locale/work/$slug'
      fullPath: '/$locale/work/$slug'
      preLoaderRoute: typeof LocaleWorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleWorkSlugRoute: LocaleWorkSlugRoute,
  LocaleExperimentsIndexRoute: LocaleExperimentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
